# Generated by Django 4.1.7 on 2023-02-15 16:56

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vehicle_type",
                    models.CharField(
                        choices=[
                            ("CAR", "Car"),
                            ("BIKE", "Bike"),
                            ("JEEP", "Jeep"),
                            ("VAN", "Van"),
                        ],
                        max_length=32,
                    ),
                ),
                ("brand_name", models.CharField(max_length=32)),
                ("vehicle_model", models.CharField(max_length=16)),
                ("color", models.CharField(max_length=16)),
                ("plate_number", models.CharField(max_length=32)),
            ],
        ),
    ]
