# Generated by Django 4.1.7 on 2023-02-23 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("parking", "0002_vehicle_owner"),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lat", models.FloatField()),
                ("long", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="ParkingSpace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_occupied", models.BooleanField()),
                ("rate_per_hour", models.IntegerField()),
                (
                    "occupied_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ParkingLot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lot_name", models.CharField(max_length=32)),
                ("lot_capacity", models.IntegerField()),
                ("occupied_spaces", models.IntegerField()),
                ("hourly_rate", models.IntegerField()),
                ("revenue", models.IntegerField()),
                ("manager", models.CharField(max_length=32)),
                (
                    "lot_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="parking.location",
                    ),
                ),
                ("parking_spaces", models.ManyToManyField(to="parking.parkingspace")),
            ],
        ),
    ]
