# Generated by Django 4.1.7 on 2023-03-06 05:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("parking", "0007_parkingsession_user_parkingspace_occupied_by_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="parkinglot",
            name="lot_location",
        ),
        migrations.AddField(
            model_name="parkinglot",
            name="lat",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="parkinglot",
            name="long",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name="Location",
        ),
    ]
