# Generated by Django 4.1.7 on 2023-03-07 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0009_remove_parkinglot_parking_spaces_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkingspace',
            name='rate_per_hour',
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='address',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='rate_per_hour',
            field=models.FloatField(default=20),
            preserve_default=False,
        ),
    ]
