# Generated by Django 4.1.7 on 2023-03-06 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("parking", "0009_remove_parkinglot_parking_spaces_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicle",
            name="owner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vehicles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
