# Generated by Django 4.1.7 on 2023-03-08 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("parking", "0011_remove_parkinglot_parking_spaces_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parkingspace",
            name="parking_lot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="spaces",
                to="parking.parkinglot",
            ),
        ),
    ]
