# Generated by Django 4.1.7 on 2023-03-01 19:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("parking", "0006_remove_parkinglot_hourly_rate_and_more"),
        ("users", "0003_alter_customuser_access_token_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="access_token",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="refresh_token",
        ),
        migrations.AddField(
            model_name="customuser",
            name="sessions",
            field=models.ManyToManyField(blank=True, to="parking.parkingsession"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="vehicles",
            field=models.ManyToManyField(blank=True, to="parking.vehicle"),
        ),
    ]
