# Generated by Django 4.1.7 on 2023-03-06 16:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_remove_customuser_access_token_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="sessions",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="vehicles",
        ),
    ]
